apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenknis
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  - name: slave
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
  type: LoadBalancer
